USE COMPANY;
CREATE TABLE EMPLOYEE (
  ssn INT NOT NULL AUTO_INCREMENT,
  fname VARCHAR(40) NOT NULL,
  lname VARCHAR(40) NOT NULL,
  bdate DATE,
  address VARCHAR(255),
  gender varchar(1),
  salary INT,
  Dno INT,
  PRIMARY KEY (ssn)
);
CREATE TABLE DEPARTMENT (
  Dnumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Dname VARCHAR(40) NOT NULL,
  mgr_ssn INT NOT NULL ,
  mgr_start_date DATE,
  FOREIGN KEY(mgr_ssn) REFERENCES EMPLOYEE(ssn) 
);
ALTER TABLE EMPLOYEE
ADD FOREIGN KEY(Dno)
REFERENCES DEPARTMENT(Dnumber);
CREATE TABLE PROJECT (
  Pnumber INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Pname VARCHAR(40) NOT NULL,
  Plocation varchar(255),
  Dno INT NOT NULL,
  FOREIGN KEY(Dno) REFERENCES DEPARTMENT(Dnumber) 
);
